class_names = [
    'Pedestrian',
    'Cyclist',
    'Car',
    'Truck',
]
data_root = 'data/tj4d/'
dataset_type = 'TJ4DDataset'
default_hooks = dict(
    checkpoint=dict(
        interval=1,
        max_keep_ckpts=5,
        save_best='Kitti metric/pred_instances_3d/KITTI/Overall_3D_moderate',
        rule='greater',
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = 'work_dirs/centerpoint_voxel005_second_secfpn_8xb4-cyclic-20e_tj4d_mm/epoch_20.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
model = dict(
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='Det3DDataPreprocessor',
        voxel=True,
        voxel_layer=dict(
            max_num_points=10,
            max_voxels=(
                16000,
                40000,
            ),
            point_cloud_range=[
                0,
                -40,
                -4,
                70.4,
                40,
                2,
            ],
            voxel_size=[
                0.05,
                0.05,
                0.125,
            ])),
    img_backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(
            checkpoint=
            'checkpoints/htc_r50_fpn_coco-20e_20e_nuim_20201008_211415-d6c60a2c.pth',
            prefix='backbone.',
            type='Pretrained'),
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='pytorch',
        type='mmdet.ResNet'),
    img_neck=dict(
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        init_cfg=dict(
            checkpoint=
            'checkpoints/htc_r50_fpn_coco-20e_20e_nuim_20201008_211415-d6c60a2c.pth',
            prefix='neck.',
            type='Pretrained'),
        num_outs=5,
        out_channels=256,
        type='mmdet.FPN'),
    pts_backbone=dict(
        conv_cfg=dict(bias=False, type='Conv2d'),
        in_channels=256,
        layer_nums=[
            5,
            5,
        ],
        layer_strides=[
            1,
            2,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN'),
        out_channels=[
            128,
            256,
        ],
        type='SECOND'),
    pts_bbox_head=dict(
        bbox_coder=dict(
            code_size=7,
            max_num=500,
            task_max_num=[
                700,
                700,
                500,
                600,
            ],
            out_size_factor=8,
            pc_range=[
                0,
                -40,
            ],
            post_center_range=[
                0,
                -40,
                -4,
                70.4,
                40,
                2,
            ],
            score_threshold=0.1,
            type='CenterPointBBoxCoder',
            voxel_size=[
                0.05,
                0.05,
            ]),
        common_heads=dict(
            dim=(
                3,
                2,
            ), height=(
                1,
                2,
            ), reg=(
                2,
                2,
            ), rot=(
                2,
                2,
            )),
        in_channels=512,
        task_loss_weights=[
            1.35,
            1.25,
            1.0,
            1.15,
        ],
        task_score_thresholds=[
            0.004,
            0.005,
            0.01,
            0.006,
        ],
        task_nms_thr=[
            0.15,
            0.15,
            0.2,
            0.18,
        ],
        task_score_gamma=[
            0.85,
            0.9,
            1.0,
            1.0,
        ],
        task_small_object_max_dim=[
            1.3,
            2.2,
            100.0,
            100.0,
        ],
        task_small_nms_thr=[
            0.12,
            0.12,
            0.2,
            0.18,
        ],
        task_small_post_max_size=[
            180,
            180,
            83,
            83,
        ],
        task_min_keep_candidates=[
            220,
            220,
            0,
            0,
        ],
        task_pre_max_size=[
            1400,
            1400,
            1000,
            1000,
        ],
        task_post_max_size=[
            120,
            120,
            83,
            83,
        ],
        task_min_radius=[
            4,
            3,
            2,
            2,
        ],
        task_gaussian_overlap=[
            0.08,
            0.09,
            0.1,
            0.1,
        ],
        loss_bbox=dict(
            loss_weight=0.25, reduction='mean', type='mmdet.L1Loss'),
        loss_cls=dict(reduction='mean', type='mmdet.GaussianFocalLoss'),
        norm_bbox=True,
        separate_head=dict(
            final_kernel=3, init_bias=-2.19, type='SeparateHead'),
        share_conv_channel=256,
        tasks=[
            dict(class_names=[
                'Pedestrian',
            ], num_class=1),
            dict(class_names=[
                'Cyclist',
            ], num_class=1),
            dict(class_names=[
                'Car',
            ], num_class=1),
            dict(class_names=[
                'Truck',
            ], num_class=1),
        ],
        type='CenterHead'),
    pts_middle_encoder=dict(
        block_type='basicblock',
        encoder_channels=(
            (
                32,
                32,
            ),
            (
                64,
                64,
                64,
            ),
            (
                128,
                128,
                128,
            ),
            (
                128,
                128,
                128,
            ),
        ),
        encoder_paddings=(
            (
                0,
                0,
            ),
            (
                1,
                0,
                0,
            ),
            (
                1,
                0,
                0,
            ),
            (
                [
                    0,
                    1,
                    1,
                ],
                0,
                0,
            ),
        ),
        in_channels=5,
        legacy=True,
        order=(
            'conv',
            'norm',
            'act',
        ),
        output_channels=128,
        point_cloud_range=[
            0,
            -40,
            -4,
            70.4,
            40,
            2,
        ],
        sparse_shape=[
            49,
            1600,
            1408,
        ],
        type='SparseEncoderFuse',
        voxel_size=[
            0.05,
            0.05,
            0.125,
        ]),
    pts_neck=dict(
        in_channels=[
            128,
            256,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN'),
        out_channels=[
            256,
            256,
        ],
        type='SECONDFPN',
        upsample_cfg=dict(bias=False, type='deconv'),
        upsample_strides=[
            1,
            2,
        ],
        use_conv_for_no_stride=True),
    pts_voxel_encoder=dict(num_features=5, type='HardSimpleVFE'),
    test_cfg=dict(
        pts=dict(
            max_per_img=500,
            max_pool_nms=False,
            min_radius=[
                4,
                12,
                10,
                1,
                0.85,
                0.175,
            ],
            nms_thr=0.2,
            nms_type='rotate',
            out_size_factor=8,
            pc_range=[
                0,
                -40,
            ],
            post_center_limit_range=[
                0,
                -40,
                -4,
                70.4,
                40,
                2,
            ],
            post_max_size=83,
            pre_max_size=1000,
            score_threshold=0.005,
            voxel_size=[
                0.05,
                0.05,
            ])),
    train_cfg=dict(
        pts=dict(
            code_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            dense_reg=1,
            gaussian_overlap=0.1,
            grid_size=[
                1408,
                1600,
                48,
            ],
            max_objs=500,
            min_radius=2,
            out_size_factor=8,
            point_cloud_range=[
                0,
                -40,
                -4,
                70.4,
                40,
                2,
            ],
            voxel_size=[
                0.05,
                0.05,
                0.125,
            ])),
    type='CenterPointFuse')
optim_wrapper = dict(
    clip_grad=dict(max_norm=10, norm_type=2),
    optimizer=dict(
        betas=(
            0.95,
            0.99,
        ), lr=0.001, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
param_scheduler = [
    dict(
        by_epoch=True,
        div_factor=10.0,
        eta_max=0.001,
        final_div_factor=10000.0,
        pct_start=0.4,
        total_steps=20,
        type='OneCycleLR'),
]
point_cloud_range = [
    0,
    -40,
    -4,
    70.4,
    40,
    2,
]
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='tj4d_infos_val.pkl',
        data_prefix=dict(
            img='training/image_2', pts='training/velodyne_reduced'),
        data_root='data/tj4d/',
        metainfo=dict(classes=[
            'Pedestrian',
            'Cyclist',
            'Car',
            'Truck',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=8,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    7,
                    5,
                ]),
            dict(
                backend_args=None,
                color_type='unchanged',
                to_float32=False,
                type='LoadImageFromFile'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(type='RandomFlip3D'),
                    dict(
                        point_cloud_range=[
                            0,
                            -40,
                            -4,
                            70.4,
                            40,
                            2,
                        ],
                        type='PointsRangeFilter'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(keys=[
                'points',
                'img',
            ], type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='TJ4DDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='data/tj4d/tj4d_infos_val.pkl',
    backend_args=None,
    metric='bbox',
    type='TJ4DMetric')
test_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=8,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            7,
            5,
        ]),
    dict(
        backend_args=None,
        color_type='unchanged',
        to_float32=False,
        type='LoadImageFromFile'),
    dict(
        flip=False,
        img_scale=(
            1333,
            800,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                rot_range=[
                    0,
                    0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0,
                    0,
                    0,
                ],
                type='GlobalRotScaleTrans'),
            dict(type='RandomFlip3D'),
            dict(
                point_cloud_range=[
                    0,
                    -40,
                    -4,
                    70.4,
                    40,
                    2,
                ],
                type='PointsRangeFilter'),
        ],
        type='MultiScaleFlipAug3D'),
    dict(keys=[
        'points',
        'img',
    ], type='Pack3DDetInputs'),
]
train_cfg = dict(max_epochs=40, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_size=16,
    dataset=dict(
        dataset=dict(
            ann_file='tj4d_infos_train.pkl',
            data_prefix=dict(
                img='training/image_2', pts='training/velodyne_reduced'),
            data_root='data/tj4d/',
            metainfo=dict(classes=[
                'Pedestrian',
                'Cyclist',
                'Car',
                'Truck',
            ]),
            modality=dict(use_camera=True, use_lidar=True),
            pipeline=[
                dict(
                    backend_args=None,
                    coord_type='LIDAR',
                    load_dim=8,
                    type='LoadPointsFromFile',
                    use_dim=[
                        0,
                        1,
                        2,
                        7,
                        5,
                    ]),
                dict(
                    backend_args=None,
                    color_type='unchanged',
                    to_float32=False,
                    type='LoadImageFromFile'),
                dict(
                    type='LoadAnnotations3D',
                    with_bbox_3d=True,
                    with_label_3d=True),
                dict(
                    flip_ratio_bev_horizontal=0.5,
                    flip_ratio_bev_vertical=0.5,
                    type='RandomFlip3D'),
                dict(
                    rot_range=[
                        -0.78539816,
                        0.78539816,
                    ],
                    scale_ratio_range=[
                        0.95,
                        1.05,
                    ],
                    type='GlobalRotScaleTrans'),
                dict(
                    point_cloud_range=[
                        0,
                        -40,
                        -4,
                        70.4,
                        40,
                        2,
                    ],
                    type='PointsRangeFilter'),
                dict(
                    point_cloud_range=[
                        0,
                        -40,
                        -4,
                        70.4,
                        40,
                        2,
                    ],
                    type='ObjectRangeFilter'),
                dict(type='PointShuffle'),
                dict(
                    keys=[
                        'points',
                        'img',
                        'gt_labels_3d',
                        'gt_bboxes_3d',
                    ],
                    type='Pack3DDetInputs'),
            ],
            type='TJ4DDataset'),
        type='CBGSDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=8,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            7,
            5,
        ]),
    dict(
        backend_args=None,
        color_type='unchanged',
        to_float32=False,
        type='LoadImageFromFile'),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),
    dict(
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5,
        type='RandomFlip3D'),
    dict(
        rot_range=[
            -0.78539816,
            0.78539816,
        ],
        scale_ratio_range=[
            0.95,
            1.05,
        ],
        type='GlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            0,
            -40,
            -4,
            70.4,
            40,
            2,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            0,
            -40,
            -4,
            70.4,
            40,
            2,
        ],
        type='ObjectRangeFilter'),
    dict(type='PointShuffle'),
    dict(
        keys=[
            'points',
            'img',
            'gt_labels_3d',
            'gt_bboxes_3d',
        ],
        type='Pack3DDetInputs'),
]
use_dim = [
    0,
    1,
    2,
    7,
    5,
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='tj4d_infos_val.pkl',
        data_prefix=dict(
            img='training/image_2', pts='training/velodyne_reduced'),
        data_root='data/tj4d/',
        metainfo=dict(classes=[
            'Pedestrian',
            'Cyclist',
            'Car',
            'Truck',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=8,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    7,
                    5,
                ]),
            dict(
                backend_args=None,
                color_type='unchanged',
                to_float32=False,
                type='LoadImageFromFile'),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(type='RandomFlip3D'),
                    dict(
                        point_cloud_range=[
                            0,
                            -40,
                            -4,
                            70.4,
                            40,
                            2,
                        ],
                        type='PointsRangeFilter'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(keys=[
                'points',
                'img',
            ], type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='TJ4DDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='data/tj4d/tj4d_infos_val.pkl',
    backend_args=None,
    metric='bbox',
    type='TJ4DMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
voxel_size = [
    0.05,
    0.05,
    0.125,
]
work_dir = './work_dirs\\centerpoint_voxel005_second_secfpn_8xb4-cyclic-20e_tj4d_mm'
